W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :subs
  
  resources :posts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W8D1/reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User
end

W8D1/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :string           not null
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord
    belongs_to :moderator,
        foreign_key: :mod_id,
        class_name: :User

    has_many :posts,
        foreign_key: :sub_id,
        class_name: :Post
end

W8D1/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }

    attr_reader :password

    after_initialize :ensure_session_token

    has_many :subs,
        foreign_key: :mod_id,
        class_name: :Sub

    has_many :authored_posts,
        foreign_key: :author_id,
        class_name: :Post 

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.base64(64)
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.base64(64)
    end
end

W8D1/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user
  #crlll

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil

    #redirect_to new_session_url  #can we do this? 
  end

  def logged_in?
    !!current_user
  end
end

W8D1/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_logged_in

    def show
        @post = Post.find(params[:id])
        render :show
    end

    def new
        @post = Post.new
        @subs = Sub.all
        render :new
    end

    def create
        #debugger
        @post = Post.new(post_params)
        @subs = Sub.all
        @post.author_id = current_user.id
        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = current_user.authored_posts.find(params[:id])
        if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def post_params
        params.require(:post).permit(:title, :url, :content, :sub_id)
    end
end

W8D1/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]
  
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
      #redirect_to        #asked if/when redirect is needed. Zach said redirect_to is a whole new request   do not render :new here after logging in a user (because they are already logged in)
    else
      flash.now[:errors] = ['Invalid username or password']
      render :new         #render :new allows the previously entered data to still be there when the page is refreshed for them to try again
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

W8D1/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in, only: [:edit, :update]

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find(params[:id]) #would be nil if sub is not found
    if @sub.update(params.require(:sub).permit(:title, :description))
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ['You need to be moderator to update this sub']
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all 
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(params.require(:sub).permit(:title, :description))
    @sub.mod_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

end

W8D1/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in, only: [:show, :update] #probably shouldn't allow random users to see all the users (index) but leaving for testing purposes

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to users_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def edit
        #@user = User.find(params[:id])
        @user = current_user
        render :edit
    end

    def update
        #@user = User.find_by_credentials(params[:user][:username], params[:user][:password]) #finds a user (with find_by_credentials username password), logs them in
        @user = current_user            #must be restricted to only_logged_in with before_action require_logged_in
        if @user.update(user_params)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:password, :username)
    end
end

W8D1/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <h1>Welcome <%= current_user.username %></h1>

    <form action="<%= session_url %>" method="POST">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <button type="submit">Logout</button>
    </form>
    <% end %>
    <%= yield %>
  </body>
</html>

W8D1/reddit_clone/app/views/posts/new.html.erb
<form action="<%= posts_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>
        Title 
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    <label>
        URL 
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>

    <label for="Content">Content</label>
    <textarea id="Content" name="post[content]" value="<%= @post.content %>">
    </textarea>

    <label for="">Choose a Sub</label>
    
    <select>
        <% @subs.each do |sub| %>
            <option name="post[sub_id]" value="4"><%= sub.title %></option>            
        <% end %>
    </select>

    <button type="submit">Create Post</button>
</form>

W8D1/reddit_clone/app/views/users/index.html.erb
<h1>Welcome to Reddit Clone!</h1>

<% @users.each do |user| %>
    <%= user.username %>
<% end %>

<a href="<%= new_user_url %>">Sign Up</a>

<a href="<%= new_session_url %>">Log In</a>

W8D1/reddit_clone/app/views/users/new.html.erb
<h1>Sign up here!</h1>

    <form action="<%= users_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <label>
            Username:
            <input type="text" name="user[username]">
        </label>
        <label>
            Password:
            <input type="text" name="user[password]">
        </label>
        <button type="submit">Sign Up</button>

    </form>

    <a href="<%= new_user_url %>">Sign Up</a>

    <a href="<%= new_session_url %>">Log In</a>